### ISSUE TITLE
Tapping on any navigation links quickly, consecutively causes navigation to not work.

### ISSUE THREAD

**Issue by yaoquan** [tapquo/Lungo.js#82]

**Comment by soyjavi** [comment]
Uhmmm... which version???

**Comment by yaoquan** [comment]
I just checked with the current one that is on demo here http://lungojs.tapquo.com/index.html . Tap any of the aside links like 3 times quickly and you'll be left with only a blank screen. Tried this on iPhone 4S

**Comment by xoan** [comment]
Related: #68, #71, #82, #83

I've been looking into the Router code, but I think that the problem is that events and transitions are triggered synchronously but executed asynchronously (maybe I'm wrong, because of concepts like these are blurry for me :)

Scenario:
1. `lng.Router.History.current()` returns `#foo`
2. Tap on `<a href="#bar" data-target="section"></a>`
3. Transition A from `#foo` to `#bar` is triggered and started
4. Tap again
5. Transition B  from `#foo`to `#bar` is triggered
6. Transition A is finished
7. `lng.Router.History.current()` returns `#bar`
8. Transition B is started, but both current and target sections are the same

I'm right?

**Comment by soyjavi** [comment]
You're right :/

2012/5/31 Xoan Sampaiño <
reply@reply.github.com

**Comment by yaoquan** [comment]
I've faced similar issues when handing db/service calls. So much so that I'm currently exploring if using state machines like https://github.com/jakesgordon/javascript-state-machine could help in elevating async callback issues.

**Comment by xoan** [comment]
On Fri, Jun 1, 2012 at 3:43 AM, Yaoquan wrote:

> I've faced similar issues when handing db/service calls. So much so that I'm currently exploring if using state machines like https://github.com/jakesgordon/javascript-state-machine could help in elevating async callback issues.

Interesting :)

## 

Xoan Sampaiño [xoan@twitter|vimeo|flickr|delicious]

 /\  Document Freedom Day - Liberate your documents
_\/` http://documentfreedom.org/ - March 28th, 2012
