### ISSUE TITLE
lng.Service.post serialization

### ISSUE THREAD

**Issue by ipedrazas** [tapquo/Lungo.js#87]
When making a Post request passing params as objects, the request fails.

var POST_DATA = {
        aparam = 'a parameter',
        another_param = 'another parameter'
    };

lng.Service.post(apiURL, POST_DATA, function(response){  
            console.error(response);
        });

But, if the params are passed inline, it works:
var POST_INLINE_DATA = "aparam=a%20parameter&another_param=another%20parameter";

lng.Service.post(apiURL, POST_INLINE_DATA , function(response){  
            console.error(response);
        });

**Comment by haas85** [comment]
You can serialize de parameters with quo:

Quo.serializeParameters({})

**Comment by erobit** [comment]
Your post data should use : instead of =, for assignment. Run it through jslint.com and you'll see... http://www.jslint.com/

var POST_DATA = {
  aparam: 'a parameter',
  another_param: 'another parameter'
};

$$.serializeParameters is already used in the $$.ajax method (used by lng.Service.post) in the quojs library, so as long as you pass in valid json, you should be off to the races.
